FROM python:3.11.4-slim-buster
LABEL maintainer="ochernyi04@gmail.com"

WORKDIR app/


ENV PYTHONUNBUFFERED 1


RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


COPY . .


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

#RUN mkdir -p /vol/web/media
#
#RUN adduser \
#    --disabled-password \
#    --no-create-home \
#    django-user
#
#RUN chown -R django-user:django-user /vol/
#RUN chmod -R 755 /vol/web/
#
#USER django-user