# Generated by Django 4.2.5 on 2023-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="article",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="fabric",
        ),
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="product",
            name="season",
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Shirts", "Shirts"),
                    ("Sweatshirts", "Sweatshirts"),
                    ("Hoodies", "Hoodies"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
