# Generated by Django 4.2.5 on 2023-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_en_description_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[("Black", "Black"), ("White", "White")],
                default="Black",
                max_length=50,
                null=True,
            ),
        ),
    ]
