# Generated by Django 4.2.5 on 2023-11-08 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 8, 21, 36, 38, 385181)
            ),
        ),
    ]
