# Generated by Django 4.2.5 on 2023-11-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_cart_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
