# Generated by Django 4.2.5 on 2023-10-03 18:47

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                (
                    "photo",
                    models.ImageField(upload_to=shop.models.news_image_file_path),
                ),
                ("color", models.CharField(max_length=55)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unisex")],
                        max_length=1,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("Su", "Summer"),
                            ("A", "Autumn"),
                            ("W", "Winter"),
                            ("Sp", "Spring"),
                        ],
                        max_length=2,
                    ),
                ),
                ("fabric", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.size",
                    ),
                ),
            ],
        ),
    ]
