# Generated by Django 4.2.5 on 2023-10-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_gender_alter_product_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unisex")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="season",
            field=models.CharField(
                choices=[
                    ("Su", "Summer"),
                    ("A", "Autumn"),
                    ("W", "Winter"),
                    ("Sp", "Spring"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.size",
            ),
        ),
    ]
