# Generated by Django 4.2.5 on 2023-10-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_category_alter_product_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
