# Generated by Django 4.2.5 on 2023-10-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_product_category_remove_product_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name_plural": "sizes"},
        ),
    ]
